services:
  # Service A: Message Queue (Pusat Logistik)
  queue: 
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15673:15672" # Dashboard
      - "5673:5672"   # Komunikasi internal
    # TIDAK ADA depends_on (dimulai duluan)

  # Service #2: Prosesor Data & AI (Dapur Utama)
  process:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678" # Port utama: Webhook, UI, dan Google OAuth
    volumes:
      - ./n8n-processor-data:/home/node/.n8n
    environment:
      TZ: Asia/Jakarta
      N8N_HOST: 119.28.110.17
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_SECURE_COOKIE: "false" # Matikan cookie securit
      DB_SQLITE_POOL_SIZE: "5"
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
      N8N_WEBHOOK_URL: http://119.28.110.17:5678
    depends_on:
      - db
      - backend
      

  # Service #4: Frontend Web (Restoran)
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - "3000:80" # Akses web publik
    volumes:
      - ./frontend-build:/usr/share/nginx/html
    depends_on:
      - backend

  # Service #5: Database MySQL (Penyimpanan Data)
  db:
    image: mysql:8.0
    restart: always
    command: --default-time-zone='+07:00'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chatbot_history
      MYSQL_USER: Alex
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Service #6: Backend API (Manajer Toko)
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: Alex
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: chatbot_history
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
